spring:
  application:
    name: mercado-livro
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=mercado_livro_db
    username: postgres
    password: postgres
